// ─── Shared Universities Data ─────────────────────────────────────────────────
export type University = {
  id: number; name: string; short: string; emoji: string; region: string;
  type: "خاصة" | "حكومية"; rank: 1|2|3|4|5;
  tuitionMin: number; tuitionMax: number; lang: string; url: string;
  majors: string[]; scholarships: boolean; acceptance: number; employRate: number;
  desc: string; founded: number; students: number; faculties: number;
  campus: string; accred: string; color: string; paths: string[]; photo?: string;
};

export const UNIVERSITIES: University[] = [
  { id:1, photo:"https://picsum.photos/seed/AUB-beirut/800/450",  name:"الجامعة الأمريكية في بيروت",      short:"AUB",  emoji:"🏛️", region:"بيروت",           type:"خاصة",   rank:5, tuitionMin:16000, tuitionMax:22000, lang:"إنجليزي",        url:"https://www.aub.edu.lb",       majors:["هندسة الحاسوب","الطب البشري","إدارة الأعمال","العلوم الطبيعية","الآداب والعلوم الإنسانية","العمارة والتصميم","الصحة العامة","الاقتصاد","الزراعة والأغذية"], scholarships:true,  acceptance:25, employRate:95, desc:"أعرق جامعة في لبنان والشرق الأوسط، تأسست عام 1866. تصنّف باستمرار ضمن أفضل 500 جامعة عالمياً وتضم أكثر من 9,000 طالب من 80+ جنسية. حائزة على اعتماد NEASC الأمريكي الرفيع.", founded:1866, students:9000,  faculties:8,  campus:"رأس بيروت",          accred:"NEASC (أمريكية)",             color:"from-[#007A53] to-[#005F3E]", paths:["هندسة","طب","أعمال","علوم الحاسوب"] },
  { id:2, photo:"https://picsum.photos/seed/LAU-lebanon/800/450",  name:"الجامعة اللبنانية الأمريكية",      short:"LAU",  emoji:"🎓", region:"بيروت وبيبلوس",  type:"خاصة",   rank:5, tuitionMin:12000, tuitionMax:18000, lang:"إنجليزي",        url:"https://www.lau.edu.lb",       majors:["هندسة الحاسوب","إدارة الأعمال","التمريض","العلاج الطبيعي","الصيدلة","الإعلام والاتصال","الحقوق","العلوم السياسية"], scholarships:true,  acceptance:35, employRate:92, desc:"جامعة مرموقة بحرمين في بيروت وبيبلوس، تأسست عام 1924. تتميز بقوة برامج التمريض والهندسة وتمنح درجات الدكتوراه في عدة تخصصات.", founded:1924, students:8500,  faculties:6,  campus:"بيروت وبيبلوس",     accred:"NEASC (أمريكية)",             color:"from-[#8B1A1A] to-[#6B0F0F]", paths:["هندسة","أعمال","تمريض","الصيدلة"] },
  { id:3, photo:"https://picsum.photos/seed/USJ-jesuits/800/450",  name:"جامعة القديس يوسف",                short:"USJ",  emoji:"⚜️", region:"بيروت",           type:"خاصة",   rank:5, tuitionMin:4000,  tuitionMax:10000, lang:"فرنسي/عربي",     url:"https://www.usj.edu.lb",       majors:["الطب البشري","القانون","العلوم السياسية","الفلسفة","الصيدلة","طب الأسنان","الهندسة","الترجمة"], scholarships:true,  acceptance:40, employRate:88, desc:"جامعة يسوعية كاثوليكية تأسست عام 1875، رائدة في التعليم الفرنكوفوني. تضم أكثر من 12,000 طالب في 13 كلية وتتميز بكليات الطب والقانون العريقة.", founded:1875, students:12000, faculties:13, campus:"بيروت (متعدد)",        accred:"اعتماد فرنسي ولبناني",       color:"from-[#1A3A5C] to-[#0F2540]", paths:["طب","قانون","دبلوماسية","صيدلة"] },
  { id:4, photo:"https://picsum.photos/seed/UL-national/800/450",  name:"الجامعة اللبنانية",                short:"UL",   emoji:"🏫", region:"كل لبنان",        type:"حكومية", rank:5, tuitionMin:0,     tuitionMax:500,   lang:"عربي/فرنسي",     url:"https://www.ul.edu.lb",        majors:["الحقوق","الهندسة","الآداب","التربية","العلوم الاجتماعية","الطب","الفنون الجميلة","الإعلام"], scholarships:false, acceptance:70, employRate:75, desc:"الجامعة الوطنية الحكومية الوحيدة بأكثر من 85,000 طالب، تتوزع فروعها في جميع محافظات لبنان. تعليم بتكاليف رمزية يتيح فرص التعليم العالي للجميع.", founded:1951, students:85000, faculties:20, campus:"فروع في كل لبنان",    accred:"وزارة التربية اللبنانية",    color:"from-[#CC0000] to-[#990000]", paths:["تربية","قانون","هندسة","اجتماع"] },
  { id:5, photo:"https://picsum.photos/seed/USEK-holy/800/450",  name:"جامعة الروح القدس الكسليك",        short:"USEK", emoji:"🎵", region:"جبل لبنان",       type:"خاصة",   rank:4, tuitionMin:5000,  tuitionMax:9000,  lang:"فرنسي/عربي",     url:"https://www.usek.edu.lb",      majors:["الفنون الجميلة","الموسيقى","العمارة","الإعلام","العلوم","الأعمال","اللاهوت","التصميم الغرافيكي"], scholarships:true,  acceptance:45, employRate:82, desc:"جامعة مارونية في الكسليك تأسست عام 1961، متميزة في الفنون والموسيقى والعمارة. تقع وسط الطبيعة اللبنانية الخلابة.", founded:1961, students:5500,  faculties:7,  campus:"الكسليك، جبيل",     accred:"اعتماد لبناني وفرنسي",       color:"from-[#4A1C5C] to-[#2D1040]", paths:["فنون","إعلام","عمارة","موسيقى"] },
  { id:6, photo:"https://picsum.photos/seed/UOB-balamand/800/450",  name:"جامعة البلمند",                    short:"UOB",  emoji:"🏔️", region:"الشمال",          type:"خاصة",   rank:4, tuitionMin:5500,  tuitionMax:9000,  lang:"إنجليزي",        url:"https://www.balamand.edu.lb",  majors:["الطب البشري","الهندسة المدنية","الفنون المعمارية","العلوم","إدارة الأعمال","التربية","علم النفس"], scholarships:true,  acceptance:42, employRate:85, desc:"جامعة أرثوذكسية أسسها الكرسي الأنطاكي عام 1988. تقع على تلة مطلة على البحر قرب الكورة وتتميز في الطب والهندسة.", founded:1988, students:4500,  faculties:6,  campus:"البلمند، الكورة",    accred:"NEASC (أمريكية)",             color:"from-[#003087] to-[#001F5B]", paths:["طب","هندسة","عمارة","علوم"] },
  { id:7, photo:"https://picsum.photos/seed/NDU-notre/800/450",  name:"جامعة سيدة اللويزة",              short:"NDU",  emoji:"⛰️", region:"جبل لبنان",       type:"خاصة",   rank:4, tuitionMin:5000,  tuitionMax:8500,  lang:"إنجليزي",        url:"https://www.ndu.edu.lb",       majors:["الهندسة","الأعمال","الإعلام والاتصال","اللاهوت","العلوم","التربية","الحقوق"], scholarships:true,  acceptance:48, employRate:83, desc:"جامعة مارونية تأسست عام 1987 في لويزة، جبل لبنان. تتميز بتعليم متكامل يجمع الأكاديمي والروحي والإنساني.", founded:1987, students:5000,  faculties:5,  campus:"لويزة، كسروان",     accred:"NEASC (أمريكية)",             color:"from-[#003366] to-[#001F3F]", paths:["هندسة","أعمال","إعلام","تربية"] },
  { id:8, photo:"https://picsum.photos/seed/ESA-business/800/450",  name:"كلية إدارة الأعمال ESA",          short:"ESA",  emoji:"💼", region:"بيروت",           type:"خاصة",   rank:5, tuitionMin:12000, tuitionMax:20000, lang:"فرنسي/إنجليزي",  url:"https://www.esa.edu.lb",       majors:["MBA","إدارة الأعمال","التسويق","التمويل","ريادة الأعمال","الإدارة الدولية","التدقيق المالي"], scholarships:true,  acceptance:30, employRate:97, desc:"أفضل كلية إدارة أعمال في لبنان، بشراكة مع HEC Paris. اعتماد ثلاثي AACSB+AMBA+EQUIS. خريجوها يتقلدون مناصب القيادة في أكبر شركات العالم.", founded:1978, students:2000,  faculties:1,  campus:"وسط بيروت",         accred:"AACSB + AMBA + EQUIS",        color:"from-[#8B1538] to-[#600F27]", paths:["أعمال","تمويل","تسويق","ريادة أعمال"] },
  { id:9, photo:"https://picsum.photos/seed/UA-arab/800/450",  name:"جامعة الأنطونية",                 short:"UA",   emoji:"✝️", region:"بيروت",           type:"خاصة",   rank:3, tuitionMin:3000,  tuitionMax:6000,  lang:"فرنسي/عربي",     url:"https://www.ua.edu.lb",        majors:["الطب البشري","الصيدلة","الحقوق","العلوم الإنسانية","اللاهوت","الفلسفة","إدارة الأعمال"], scholarships:false, acceptance:55, employRate:78, desc:"جامعة كاثوليكية أنطونية متميزة في الطب والصيدلة والعلوم الإنسانية، بعلاقات وثيقة مع المؤسسات الفرنسية.", founded:1996, students:3500,  faculties:5,  campus:"حدث، الجنوبية",      accred:"اعتماد لبناني",              color:"from-[#5C3317] to-[#3D2211]", paths:["طب","صيدلة","قانون"] },
  { id:10, photo:"https://picsum.photos/seed/LIU-islamic/800/450", name:"الجامعة اللبنانية الدولية",        short:"LIU",  emoji:"🌙", region:"بيروت وفروع",    type:"خاصة",   rank:3, tuitionMin:3000,  tuitionMax:6000,  lang:"عربي/إنجليزي",   url:"https://www.liu.edu.lb",       majors:["الطب البشري","الصيدلة","الهندسة","تكنولوجيا المعلومات","الأعمال","الشريعة الإسلامية","التربية"], scholarships:true,  acceptance:60, employRate:76, desc:"جامعة إسلامية خاصة تأسست 1996 بفروع في أنحاء لبنان. تقدم تعليماً ميسوراً مع التزام بالقيم الإسلامية وتضم أكثر من 20,000 طالب.", founded:1996, students:20000, faculties:8,  campus:"فروع في كل لبنان",  accred:"وزارة التربية اللبنانية",    color:"from-[#006B3C] to-[#004D2B]", paths:["طب","صيدلة","هندسة","تكنولوجيا"] },
  { id:11, photo:"https://picsum.photos/seed/HU-holy-spirit/800/450", name:"جامعة هايكازيان",                 short:"HU",   emoji:"🔵", region:"بيروت",           type:"خاصة",   rank:3, tuitionMin:4000,  tuitionMax:7000,  lang:"إنجليزي",        url:"https://www.haigazian.edu.lb", majors:["الآداب الإنجليزية","العلوم الإنسانية","التربية","علم النفس","الفلسفة","الدراسات الأرمنية"], scholarships:true,  acceptance:65, employRate:74, desc:"جامعة أرمنية بروتستانتية تأسست عام 1955. أصغر جامعة خاصة في لبنان وتتميز بجو أكاديمي حميمي وشخصي.", founded:1955, students:1200,  faculties:3,  campus:"شياح، بيروت",       accred:"NEASC (أمريكية)",             color:"from-[#003087] to-[#001F5B]", paths:["تربية","آداب","علوم إنسانية"] },
  { id:12, photo:"https://picsum.photos/seed/ALBA-arts/800/450", name:"الأكاديمية اللبنانية للفنون",     short:"ALBA", emoji:"🎨", region:"بيروت",           type:"خاصة",   rank:4, tuitionMin:5000,  tuitionMax:8000,  lang:"فرنسي",          url:"https://www.alba.edu.lb",      majors:["الفنون البصرية","الهندسة المعمارية","التصميم الغرافيكي","التصميم الداخلي","الفنون التطبيقية","التصوير الفوتوغرافي"], scholarships:false, acceptance:35, employRate:80, desc:"مدرسة الفنون الجميلة الأرقى في لبنان والعالم العربي، تأسست عام 1937. خريجوها يُضيئون المشهد الإبداعي عالمياً.", founded:1937, students:1500,  faculties:2,  campus:"عشرفية، بيروت",     accred:"اعتماد فرنسي",               color:"from-[#1A1A1A] to-[#333333]", paths:["تصميم","عمارة","فنون بصرية"] },
  { id:13, photo:"https://picsum.photos/seed/UJ-jinan/800/450", name:"جامعة الجنان",                    short:"UJ",   emoji:"🌿", region:"الشمال (طرابلس)",type:"خاصة",   rank:3, tuitionMin:2500,  tuitionMax:5500,  lang:"عربي/إنجليزي",   url:"https://www.jinan.edu.lb",     majors:["الهندسة المعلوماتية","إدارة الأعمال","الحقوق","التربية","الإعلام والاتصال","علم النفس","المحاسبة"], scholarships:true,  acceptance:65, employRate:72, desc:"جامعة خاصة تأسست عام 1994 في طرابلس، من أبرز المؤسسات التعليمية في شمال لبنان. تقدم تعليماً معياراً بأسعار معقولة لخدمة طلاب المنطقة.", founded:1994, students:6000,  faculties:6,  campus:"طرابلس",             accred:"وزارة التربية اللبنانية",    color:"from-[#2D6A4F] to-[#1B4332]", paths:["هندسة","أعمال","قانون","إعلام"] },
  { id:14, photo:"https://picsum.photos/seed/IAU-ouzai/800/450", name:"جامعة الإمام الأوزاعي",           short:"IAU",  emoji:"🕌", region:"بيروت (غرب)",    type:"خاصة",   rank:2, tuitionMin:2000,  tuitionMax:4500,  lang:"عربي",            url:"https://www.ouzai.org",        majors:["الشريعة الإسلامية","الحقوق","أصول الدين","الدراسات الإسلامية","التربية الإسلامية","اللغة العربية"], scholarships:true,  acceptance:70, employRate:70, desc:"جامعة إسلامية تأسست عام 1979 في بيروت الغربية، تتخصص في الدراسات الشرعية والإسلامية وتُربّي أجيالاً من العلماء والمفكرين.", founded:1979, students:3000,  faculties:4,  campus:"بيروت الغربية",     accred:"وزارة التربية اللبنانية",    color:"from-[#2C5F2E] to-[#1A3D1B]", paths:["شريعة","قانون","تربية"] },
  { id:15, photo:"https://picsum.photos/seed/LGU-global/800/450", name:"الجامعة الألمانية اللبنانية",      short:"LGU",  emoji:"🇩🇪", region:"جبل لبنان",       type:"خاصة",   rank:3, tuitionMin:4000,  tuitionMax:8000,  lang:"إنجليزي/ألماني", url:"https://www.lgu.edu.lb",       majors:["إدارة الأعمال الدولية","هندسة الميكاترونيك","علوم الكمبيوتر","الهندسة الصناعية","اللوجستيات"], scholarships:true,  acceptance:50, employRate:83, desc:"جامعة خاصة تأسست عام 2008 بتعاون مع مؤسسات ألمانية في سهل علما. تتميز ببرامجها التطبيقية وتمنح طلابها فرص التدريب في ألمانيا.", founded:2008, students:2500,  faculties:4,  campus:"سهل علما، كسروان",  accred:"اعتماد لبناني وألماني",       color:"from-[#1F3864] to-[#16284D]", paths:["هندسة","أعمال دولية","تكنولوجيا"] },
  { id:16, photo:"https://picsum.photos/seed/EIU-tripoli/800/450", name:"جامعة العزم — East International University (EIU)", short:"EIU",  emoji:"⚡", region:"الشمال (طرابلس)",type:"خاصة",   rank:2, tuitionMin:2500,  tuitionMax:5000,  lang:"عربي/إنجليزي",   url:"https://www.eiu.edu.lb",       majors:["تكنولوجيا المعلومات","الصيدلة","العلوم الطبية المساعدة","إدارة الأعمال","الهندسة الكهربائية"], scholarships:true,  acceptance:60, employRate:71, desc:"جامعة خاصة في طرابلس تأسست عام 2015 (سابقاً جامعة العزم Azm University). تُركّز على العلوم والتكنولوجيا والصحة وتُغيّرت تسميتها رسمياً إلى East International University (EIU).", founded:2015, students:3500,  faculties:5,  campus:"طرابلس",             accred:"وزارة التربية اللبنانية",    color:"from-[#0F4C75] to-[#0A3356]", paths:["تكنولوجيا","صيدلة","أعمال"] },
  { id:17, photo:"https://picsum.photos/seed/UC-kafaat/800/450", name:"جامعة الكفاءات",                  short:"UC",   emoji:"🎯", region:"بيروت (ضاحية)",  type:"خاصة",   rank:3, tuitionMin:2000,  tuitionMax:4500,  lang:"فرنسي/عربي",     url:"https://www.uc.edu.lb",        majors:["التربية الخاصة","العلوم الصحية","العلاج الطبيعي","التمريض","إدارة الأعمال","الحقوق"], scholarships:false, acceptance:65, employRate:75, desc:"جامعة متخصصة في علوم الصحة والتربية الخاصة تأسست في فرن الشباك. تتميز في برامج التأهيل والتربية الخاصة.", founded:1999, students:2500,  faculties:4,  campus:"فرن الشباك، بيروت", accred:"اعتماد لبناني",              color:"from-[#6A0572] to-[#4A0350]", paths:["تربية خاصة","صحة","تمريض"] },
  { id:18, photo:"https://picsum.photos/seed/UIL-islamic/800/450", name:"الجامعة الإسلامية في لبنان",       short:"UIL",  emoji:"☪️", region:"الجنوب",          type:"خاصة",   rank:2, tuitionMin:1500,  tuitionMax:4000,  lang:"عربي",            url:"https://www.iul.edu.lb",       majors:["الشريعة والقانون","الاقتصاد الإسلامي","التربية","العلوم الإنسانية","إدارة الأعمال"], scholarships:false, acceptance:75, employRate:68, desc:"جامعة إسلامية تأسست في خلدة عام 2003. تُقدّم تعليماً ملتزماً بالقيم الإسلامية بأسعار في متناول الجميع.", founded:2003, students:4000,  faculties:4,  campus:"خلدة، الجنوب",      accred:"وزارة التربية اللبنانية",    color:"from-[#1B4332] to-[#0E2B1E]", paths:["شريعة","قانون","تربية"] },
  { id:19, photo:"https://picsum.photos/seed/UT-tripoli/800/450", name:"جامعة طرابلس",                    short:"UT",   emoji:"🏙️", region:"الشمال (طرابلس)",type:"خاصة",   rank:2, tuitionMin:2000,  tuitionMax:4500,  lang:"عربي/إنجليزي",   url:"https://www.ut.edu.lb",        majors:["الهندسة المدنية","الأعمال","القانون","تكنولوجيا المعلومات","التربية","الإعلام"], scholarships:false, acceptance:72, employRate:70, desc:"جامعة خاصة في طرابلس تأسست عام 2000 لخدمة طلاب الشمال. تتميز بأقساطها الميسورة وبرامجها العملية.", founded:2000, students:5000,  faculties:5,  campus:"طرابلس",             accred:"وزارة التربية اللبنانية",    color:"from-[#1C4E80] to-[#103460]", paths:["هندسة","أعمال","قانون"] },
  { id:20, photo:"https://picsum.photos/seed/CityU-madina/800/450", name:"جامعة المدينة (سابقاً جامعة المنار)", short:"CityU", emoji:"🏙️", region:"الشمال", type:"خاصة", rank:2, tuitionMin:1800, tuitionMax:4000, lang:"عربي/فرنسي", url:"https://cityu.edu.lb", majors:["الطب العام","الصيدلة","الحقوق","إدارة الأعمال","التربية","المحاسبة"], scholarships:false, acceptance:70, employRate:69, desc:"جامعة خاصة في طرابلس، عُرفت سابقاً بجامعة المنار. تأسست عام 2004 وغيّرت اسمها رسمياً إلى جامعة المدينة بمرسوم لبناني.", founded:2004, students:3000, faculties:4, campus:"طرابلس", accred:"وزارة التربية اللبنانية", color:"from-[#344E41] to-[#213329]", paths:["طب","صيدلة","قانون"] },
  { id:21, photo:"https://picsum.photos/seed/US-sagesse/800/450", name:"جامعة الحكمة",                    short:"US",   emoji:"🌟", region:"المتن",           type:"خاصة",   rank:3, tuitionMin:4000,  tuitionMax:8000,  lang:"فرنسي/عربي",     url:"https://www.uls.edu.lb",       majors:["إدارة الأعمال","الهندسة","الحقوق والعلوم السياسية","الآداب والعلوم الإنسانية","الإعلام","التربية"], scholarships:true,  acceptance:50, employRate:77, desc:"جامعة لبنانية ذات طابع مسيحي تأسست في ديك المحدي. تتميز بأجوائها الهادئة وبرامجها الفرنسية الموجهة.", founded:1999, students:3500,  faculties:5,  campus:"ديك المحدي، المتن", accred:"اعتماد لبناني وفرنسي",       color:"from-[#7D5A50] to-[#5C3D35]", paths:["أعمال","هندسة","قانون"] },
  { id:22, photo:"https://picsum.photos/seed/CUB-cairo/800/450", name:"جامعة القاهرة — فرع بيروت",      short:"CUB",  emoji:"🌍", region:"بيروت",           type:"خاصة",   rank:3, tuitionMin:2500,  tuitionMax:5000,  lang:"عربي",            url:"https://www.cairo.edu.lb",     majors:["الحقوق","الاقتصاد والعلوم السياسية","الآداب","التجارة","إعلام وعلوم الاتصال"], scholarships:false, acceptance:60, employRate:73, desc:"فرع جامعة القاهرة المرموقة في لبنان. يتيح للطلاب اللبنانيين الحصول على شهادة الجامعة المصرية العريقة بأسعار مناسبة.", founded:1994, students:4500,  faculties:5,  campus:"بيروت",              accred:"جامعة القاهرة / وزارة التربية",color:"from-[#A0522D] to-[#6B3520]", paths:["قانون","اقتصاد","آداب","إعلام"] },
  { id:23, photo:"https://picsum.photos/seed/BAU-arab/800/450", name:"جامعة بيروت العربية", short:"BAU", emoji:"🕌", region:"بيروت", type:"خاصة", rank:5, tuitionMin:4000, tuitionMax:8000, lang:"عربي/إنجليزي", url:"https://www.bau.edu.lb", majors:["الهندسة","الطب","العلوم","إدارة الأعمال","الحقوق","التمريض","الصيدلة","العمارة","الإعلام"], scholarships:true, acceptance:50, employRate:85, desc:"جامعة خاصة عريقة تأسست عام 1960 بدعم من جامعة الإسكندرية. تُصنّف ضمن أفضل الجامعات العربية (المرتبة 31 إقليمياً QS 2026) وتضم أكثر من 11,000 طالب.", founded:1960, students:11000, faculties:10, campus:"بيروت — طرابلس — البقاع", accred:"وزارة التربية اللبنانية", color:"from-[#0B6E4F] to-[#063D2C]", paths:["هندسة","طب","قانون","أعمال"] }
];

export type Review = { name: string; rating: number; year: string; text: string; };

export const REVIEWS: Record<number, Review[]> = {
  1: [
    { name:"أحمد م.", rating:5, year:"خريج 2024",   text:"تجربة استثنائية. الأساتذة من أفضل ما يكون والبيئة الأكاديمية لا مثيل لها في المنطقة." },
    { name:"سارة ك.", rating:5, year:"طالبة حالية", text:"الحرم الجامعي رائع والنشاطات اللاصفية كثيرة. الشبكة الطلابية قيّمة جداً." },
    { name:"علي ت.",  rating:4, year:"خريج 2023",   text:"التعليم ممتاز لكن الرسوم مرتفعة جداً. لحسن الحظ المنح متوفرة لمن يستحق." },
  ],
  2: [
    { name:"مريم ح.", rating:5, year:"خريجة 2024",  text:"LAU غيّرت حياتي. الحرم في بيروت جميل وعلاقات الخريجين قوية جداً." },
    { name:"كريم ز.", rating:4, year:"طالب حالي",   text:"برنامج التمريض من الأقوى في لبنان. التدريب العملي ممتاز." },
    { name:"نور س.",  rating:4, year:"خريج 2023",   text:"الهندسة قوية وأساتذة متمرسون. الحياة الجامعية في بيروت رائعة." },
  ],
  3: [
    { name:"لارا ب.", rating:5, year:"خريجة 2024",  text:"كلية الحقوق في USJ لا مثيل لها. التعليم الفرنسي أتاح لي فرصاً دولية." },
    { name:"جورج ع.", rating:4, year:"طالب حالي",   text:"كلية الطب صعبة لكنها تؤهلك تأهيلاً عالياً. المشافي التدريبية ممتازة." },
    { name:"هند م.",  rating:4, year:"خريجة 2022",  text:"الجو اليسوعي يشجع على التفكير النقدي. تجربة غنية على كل الأصعدة." },
  ],
  4: [
    { name:"رامي خ.", rating:4, year:"خريج 2024",   text:"تعليم جيد بسعر مناسب جداً. الجامعة اللبنانية أتاحت للجميع الحصول على شهادة." },
    { name:"إيمان ف.",rating:3, year:"طالبة حالية", text:"البنية التحتية تحتاج تطوير لكن الأساتذة ملتزمون. المهم هو ما تستثمره أنت." },
    { name:"حسام ن.", rating:4, year:"خريج 2023",   text:"كلية الهندسة وفّرت لي أساساً قوياً وعملت بعدها في الخارج." },
  ],
  5: [
    { name:"ريتا غ.", rating:5, year:"خريجة 2024",  text:"USEK في الكسليك مكان ساحر. برنامج الموسيقى من الأفضل في المنطقة." },
    { name:"بيار ف.", rating:4, year:"طالب حالي",   text:"العمارة هنا رائعة وأساتذة متخصصون. الطبيعة حول الحرم تلهم الإبداع." },
    { name:"كلود م.", rating:5, year:"خريج 2023",   text:"جو دافئ وعائلي. التصميم الغرافيكي أهّلني لسوق العمل بسرعة." },
  ],
  6: [
    { name:"طارق ع.", rating:5, year:"طالب حالي",   text:"المنظر من الحرم رائع وكلية الطب تنافس أفضل الجامعات." },
    { name:"ميشيل ب.",rating:4, year:"خريج 2024",   text:"الهندسة المدنية قوية جداً. كثير من الخريجين يعملون في شركات دولية." },
  ],
  7: [
    { name:"ناتالي ك.",rating:4, year:"خريجة 2024", text:"NDU تجمع التميز الأكاديمي مع القيم الإنسانية. فخورة بانتمائي لها." },
    { name:"ستيفاني م.",rating:5,year:"خريجة 2023", text:"الحياة الجامعية في NDU لا تُنسى. الأنشطة الطلابية متنوعة ومثيرة." },
  ],
  8: [
    { name:"زياد ب.", rating:5, year:"خريج MBA 2024",text:"ESA + HEC Paris = بوابة للعالم. الشبكة المهنية التي بنيتها لا تقدر بثمن." },
    { name:"ديانا ع.", rating:5, year:"خريجة 2023", text:"الأفضل في لبنان بلا منازع لمن يريد مستقبلاً في الأعمال." },
  ],
  9:  [{ name:"روز م.", rating:4, year:"خريجة 2024", text:"جامعة الأنطونية أعطتني أساساً علمياً قوياً في الصيدلة." }],
  10: [{ name:"يوسف س.", rating:4, year:"خريج 2024", text:"LIU أتاحت لي تعليماً بأسعار معقولة. توظفت بعد التخرج مباشرة." }],
  11: [{ name:"تاليا غ.", rating:5, year:"خريجة 2023",text:"جامعة صغيرة لكن ذات روح كبيرة. كل أستاذ يعرف اسمك شخصياً." }],
  12: [{ name:"ليلى ن.", rating:5, year:"خريجة 2024", text:"ALBA حوّلت شغفي بالتصميم إلى مسيرة مهنية. الأساتذة محترفون حقيقيون." }],
  13: [{ name:"رولا ف.", rating:3, year:"خريجة 2024", text:"جامعة الجنان خيار ممتاز لأبناء الشمال. سهولة الوصول والأسعار المناسبة ميزتها الكبرى." }],
  14: [{ name:"محمد ق.", rating:4, year:"خريج 2023",  text:"متميزة في الفقه الإسلامي. خرّجت علماء ومشايخ كثيرين." }],
  15: [{ name:"كارين م.", rating:4, year:"خريجة 2024",text:"LGU أعطتني منظوراً دولياً ألمانياً. تدربت في ألمانيا وحصلت على فرصة عمل هناك." }],
  16: [{ name:"أنس ر.", rating:3, year:"طالب حالي",   text:"جامعة EIU شابة لكنها تتطور بسرعة. الأسعار في متناول الجميع." }],
  17: [{ name:"فاطمة ع.", rating:3, year:"خريجة 2023",text:"جيدة للتربية الخاصة. أساتذة متخصصون ومتفانون مع الطلاب." }],
  18: [{ name:"حسن ر.", rating:3, year:"طالب حالي",   text:"ميسورة التكلفة وملتزمة بقيمها. جيدة لمن يبحث عن بيئة إسلامية." }],
  19: [{ name:"سلمى ن.", rating:3, year:"خريجة 2023", text:"خيار جيد لأبناء طرابلس. قريبة وبأسعار مناسبة." }],
  20: [{ name:"علاء ع.", rating:3, year:"طالب حالي",  text:"برنامج الصيدلة في جامعة المدينة (المنار سابقاً) متميز. أسعار جيدة لأبناء الشمال." }],
  21: [{ name:"بياتريس ك.",rating:4,year:"خريجة 2024",text:"جامعة الحكمة في محيط طبيعي جميل. البرامج الفرنسية ذات جودة عالية." }],
  22: [{ name:"نادين س.", rating:3, year:"خريجة 2023",text:"فرع جامعة القاهرة يعطيك شهادة عريقة بأسعار مناسبة." }],
  23: [{ name:"رنا ج.", rating:4, year:"خريجة 2024", text:"جامعة بيروت العربية BAU عريقة وفيها كليات متعددة. الهندسة والطب قويين." }],
};
