@echo off
echo Removing git lock...
del /f ".git\index.lock" 2>nul
echo Staging files...
git add -A
echo Committing...
git commit -m "Phase 4: StudentContext + Comparison + Dashboard 2.0 + Onboarding + Eligibility + AI Context + Mobile Nav"
echo Pushing...
git push origin main
echo Done!
pause
