// Shared majors dataset — imported by both the list page (client) and the
// SEO-indexable detail pages /majors/[slug] (server). Plain module (no "use
// client") so server components can read it for generateMetadata/Static params.
//
// Extends the original list data with: slug, nameEn (for URL/SEO), aiImpact
// (future-of-work signal), and future (Arabic outlook) — the Phase-3 career layer.
//
// Salaries: monthly USD, ENTRY-TO-MID band, deliberately conservative with tight
// ranges (see SALARY_NOTE). Per user feedback (2026-06-29) earlier figures were
// over-optimistic and ranges too wide.

export type AiImpact = "grows" | "shifts" | "at_risk";

export type Major = {
  id: number;
  slug: string;
  name: string;
  nameEn: string;
  category: string;
  emoji: string;
  years: number;
  lang: string;
  salaryMin: number;
  salaryMax: number;
  salaryGulfMin: number;
  salaryGulfMax: number;
  demandLB: "عالٍ جداً" | "عالٍ" | "متوسط" | "منخفض";
  demandGulf: "عالٍ جداً" | "عالٍ" | "متوسط" | "منخفض";
  difficulty: 1 | 2 | 3 | 4 | 5;
  careers: string[];
  desc: string;
  riasec: string;
  universities: string[];
  roadmap: string[];
  certifications?: string[];
  skills: string[];
  aiImpact: AiImpact;
  future: string;
};

/** Shown next to every salary figure — they are rough estimates, not promises. */
export const SALARY_NOTE = "تقديري — يختلف حسب الخبرة والشركة والمدينة";

export const MAJORS: Major[] = [
  { id:1, slug:"medicine", nameEn:"Medicine", name:"طب بشري", category:"الطب والصحة", emoji:"🩺", years:6, lang:"إنجليزي", salaryMin:2000, salaryMax:3500, salaryGulfMin:5000, salaryGulfMax:9000, demandLB:"عالٍ جداً", demandGulf:"عالٍ جداً", difficulty:5, careers:["طبيب عام","طبيب متخصص","باحث طبي","طب طوارئ"], desc:"أعرق التخصصات وأكثرها مكانةً. 6 سنوات دراسة + امتياز + تخصص. طلب لا ينتهي في لبنان والعالم.", riasec:"IS", universities:["AUB","LAU","USJ","UOB"], roadmap:["العلوم الطبيعية (ص10-12)","BAC علوم","MCAT/Entrance Exam","طب عام (6 سنوات)","امتياز (سنة)","تخصص (3-7 سنوات)"], certifications:["USMLE","نقابة الأطباء","Board Certification"], skills:["تشريح","فيزيولوجيا","تشخيص سريري","بحث طبي","تواصل مع المرضى"], aiImpact:"grows", future:"الطلب دائم ومتنامٍ؛ الذكاء الاصطناعي يساعد في التشخيص والتصوير لكنه لا يستبدل الطبيب." },
  { id:2, slug:"pharmacy", nameEn:"Pharmacy", name:"صيدلة", category:"الطب والصحة", emoji:"💊", years:5, lang:"إنجليزي/فرنسي", salaryMin:1200, salaryMax:2200, salaryGulfMin:2800, salaryGulfMax:4500, demandLB:"عالٍ", demandGulf:"عالٍ جداً", difficulty:4, careers:["صيدلاني","باحث دوائي","مدير صيدلية","صيدلاني سريري"], desc:"علم الدواء وتأثيراته — طلب كبير في لبنان والخليج. فرص عمل في المستشفيات والشركات الدوائية الكبرى.", riasec:"IC", universities:["AUB","USJ","LAU","LIU"], roadmap:["علوم (ص10-12)","BAC علوم","Pharmacy Entrance","5 سنوات صيدلة","تدريب سريري","PharmD اختياري"], certifications:["نقابة الصيادلة","PharmD"], skills:["كيمياء عضوية","بيوكيمياء","فارماكولوجيا","تفاعل الأدوية"], aiImpact:"shifts", future:"أتمتة الصرف تتزايد؛ القيمة المستقبليّة في الصيدلة السريريّة والبحث الدوائي لا في الصرف الروتيني." },
  { id:3, slug:"nursing", nameEn:"Nursing", name:"تمريض", category:"الطب والصحة", emoji:"🏥", years:4, lang:"إنجليزي", salaryMin:800, salaryMax:1500, salaryGulfMin:1800, salaryGulfMax:3000, demandLB:"عالٍ جداً", demandGulf:"عالٍ جداً", difficulty:3, careers:["ممرض","مشرف تمريض","ممرض ICU","مدير صحي"], desc:"الطلب يتضاعف سنوياً — أعلى معدلات التوظيف. كندا وألمانيا والخليج يستقبلون ممرضين لبنانيين.", riasec:"SI", universities:["AUB","LAU","LIU","BAU"], roadmap:["BAC علوم","Nursing Entrance","4 سنوات تمريض","تدريب مستشفى","NCLEX للهجرة"], certifications:["NCLEX-RN","BSN"], skills:["رعاية مرضى","إسعافات أولية","تواصل","تحمل ضغط"], aiImpact:"grows", future:"نقص عالمي حادّ في الممرّضين؛ مهنة آمنة من الأتمتة وبوّابة للهجرة (كندا/ألمانيا/الخليج)." },
  { id:4, slug:"dentistry", nameEn:"Dentistry", name:"طب أسنان", category:"الطب والصحة", emoji:"🦷", years:5, lang:"إنجليزي/فرنسي", salaryMin:1800, salaryMax:3500, salaryGulfMin:4000, salaryGulfMax:6500, demandLB:"عالٍ", demandGulf:"عالٍ", difficulty:4, careers:["طبيب أسنان","جراح فك","أستاذ جامعي"], desc:"تخصص يتيح العمل الحر المستقل. عيادات خاصة تبدأ أرباحها بسرعة.", riasec:"IR", universities:["USJ","LAU","BAU","LIU"], roadmap:["علوم (ص10-12)","BAC علوم","Dentistry Entrance","5 سنوات دراسة","امتياز"], certifications:["نقابة أطباء الأسنان"], skills:["دقة يدوية","تشريح الفك","تواصل مع المرضى"], aiImpact:"grows", future:"عمل حرّ مستقرّ ومربح؛ الذكاء الاصطناعي يحسّن التصوير والتشخيص لكن المهارة اليدويّة تبقى بشريّة." },
  { id:5, slug:"computer-engineering", nameEn:"Computer Engineering", name:"هندسة الحاسوب", category:"الهندسة والتكنولوجيا", emoji:"💻", years:4, lang:"إنجليزي", salaryMin:1500, salaryMax:2800, salaryGulfMin:3500, salaryGulfMax:5500, demandLB:"عالٍ جداً", demandGulf:"عالٍ جداً", difficulty:4, careers:["مطور برمجيات","مهندس AI","مدير تقني","Cloud Engineer"], desc:"تخصص المستقبل — طلب هائل محلياً وعالمياً. الشركات التقنية تنافس على خريجي AUB وLAU.", riasec:"IR", universities:["AUB","LAU","AUT","LIU"], roadmap:["رياضيات وفيزياء قوية","SAT/Entrance Exam","4 سنوات هندسة","تدريب صيفي","مشاريع GitHub","وظيفة أو ماستر"], certifications:["AWS Certified","Google Cloud","Microsoft Azure","Cisco CCNA"], skills:["Python","C++","Data Structures","System Design","SQL"], aiImpact:"grows", future:"في قلب ثورة الذكاء الاصطناعي؛ من أعلى التخصّصات طلباً ونموّاً عالميّاً." },
  { id:6, slug:"computer-science", nameEn:"Computer Science", name:"علوم الحاسوب", category:"الهندسة والتكنولوجيا", emoji:"🖥️", years:4, lang:"إنجليزي", salaryMin:1400, salaryMax:2600, salaryGulfMin:3200, salaryGulfMax:5000, demandLB:"عالٍ جداً", demandGulf:"عالٍ جداً", difficulty:4, careers:["مطور ويب","مهندس بيانات","خبير أمن","DevOps"], desc:"أساس تخصصات التقنية — أكثر مرونة من الهندسة. تعلّم برمجة، AI، أمن معلومات.", riasec:"IC", universities:["AUB","LAU","AUT","LIU"], roadmap:["رياضيات قوية","CS Entrance","4 سنوات CS","مشاريع عملية","شهادات احترافية"], certifications:["CompTIA Security+","AWS Solutions Architect","Google Data Analytics"], skills:["Python","JavaScript","Algorithms","Machine Learning","DevOps"], aiImpact:"grows", future:"أوسع أبواب التقنية مرونةً؛ نموّ مستمرّ والمهارة في التكيّف مع أدوات AI ترفع القيمة." },
  { id:7, slug:"civil-engineering", nameEn:"Civil Engineering", name:"هندسة مدنية", category:"الهندسة والتكنولوجيا", emoji:"🏗️", years:5, lang:"إنجليزي/فرنسي", salaryMin:1200, salaryMax:2200, salaryGulfMin:3000, salaryGulfMax:5000, demandLB:"متوسط", demandGulf:"عالٍ جداً", difficulty:4, careers:["مهندس إنشاءات","مخطط مدن","مقاول","مشرف ميداني"], desc:"البنية التحتية والمشاريع الكبرى. الخليج يبني ويحتاج مهندسين. نيوم وإكسبو دبي فتحا الطريق.", riasec:"RI", universities:["AUB","USJ","LAU","UOB"], roadmap:["رياضيات وفيزياء","BAC","5 سنوات هندسة مدنية","PMP أو تخصص إنشائي","وظيفة خليج"], certifications:["PMP","PE License","LEED Green Associate"], skills:["AutoCAD","SAP2000","إدارة مشاريع","رسم هندسي","تحليل إنشائي"], aiImpact:"shifts", future:"مشاريع الخليج العملاقة تدفع الطلب؛ الذكاء الاصطناعي أداة تصميم ومحاكاة لا بديل." },
  { id:8, slug:"electrical-engineering", nameEn:"Electrical Engineering", name:"هندسة كهربائية", category:"الهندسة والتكنولوجيا", emoji:"⚡", years:5, lang:"إنجليزي", salaryMin:1300, salaryMax:2400, salaryGulfMin:3200, salaryGulfMax:5000, demandLB:"عالٍ", demandGulf:"عالٍ جداً", difficulty:4, careers:["مهندس طاقة","مهندس اتصالات","مهندس تحكم","Energy Consultant"], desc:"من الطاقة المتجددة للشبكات الذكية. الإمارات والسعودية تضخ مليارات في الطاقة الخضراء.", riasec:"RI", universities:["AUB","LAU","AUT","BAU"], roadmap:["رياضيات وفيزياء","Entrance Exam","5 سنوات EE","تخصص طاقة/اتصالات","وظيفة"], certifications:["PE","PMP","Certified Energy Auditor"], skills:["MATLAB","SCADA","PLC","Circuit Analysis","Renewable Energy"], aiImpact:"grows", future:"الطاقة المتجدّدة والشبكات الذكية محرّك نموّ ضخم في الخليج لعقود قادمة." },
  { id:9, slug:"architecture", nameEn:"Architecture", name:"هندسة معمارية", category:"الهندسة والتكنولوجيا", emoji:"🏛️", years:5, lang:"إنجليزي/فرنسي", salaryMin:1100, salaryMax:2000, salaryGulfMin:2800, salaryGulfMax:4500, demandLB:"متوسط", demandGulf:"عالٍ", difficulty:4, careers:["مهندس معماري","مصمم داخلي","مخطط عمراني","BIM Specialist"], desc:"الجمع بين الفن والعلم. لبنان مشهور عالمياً بمعمارييه — ALBA وAUB من أقوى البرامج.", riasec:"AR", universities:["AUB","USJ","ALBA","NDU"], roadmap:["موهبة فنية وتقنية","Portfolio للقبول","5 سنوات عمارة","تدريب مكتب","Licensure"], certifications:["LEED AP","Autodesk Certified","BIM Professional"], skills:["AutoCAD","Revit","SketchUp","Rhino","Adobe CC","تصميم مستدام"], aiImpact:"shifts", future:"أدوات الذكاء الاصطناعي تغيّر سير العمل؛ الرؤية الإبداعيّة والتصميم المستدام يبقيان بشريّين." },
  { id:10, slug:"business-administration", nameEn:"Business Administration", name:"إدارة أعمال", category:"الأعمال والإدارة", emoji:"💼", years:4, lang:"إنجليزي/عربي", salaryMin:900, salaryMax:1800, salaryGulfMin:2500, salaryGulfMax:4500, demandLB:"عالٍ", demandGulf:"عالٍ جداً", difficulty:2, careers:["مدير تنفيذي","رائد أعمال","مستشار","مدير عمليات"], desc:"أكثر التخصصات مرونةً. ESA وAUB تفتحان أبواب الشركات الكبرى.", riasec:"EC", universities:["AUB","LAU","ESA","LIU"], roadmap:["BAC أي فرع","Entrance Exam","4 سنوات BBA","MBA بعد 5 سنوات عمل","Executive Track"], certifications:["PMP","MBA","CFA Level 1","Six Sigma"], skills:["Financial Analysis","PowerPoint","Excel","Leadership","Business Strategy"], aiImpact:"shifts", future:"تخصّص مرن؛ من يضيف مهارات البيانات والقيادة يتفوّق، ومن يكتفي بالأساسيّات يتراجع." },
  { id:11, slug:"accounting-finance", nameEn:"Accounting & Finance", name:"محاسبة وتمويل", category:"الأعمال والإدارة", emoji:"📊", years:4, lang:"إنجليزي", salaryMin:1000, salaryMax:2000, salaryGulfMin:2800, salaryGulfMax:4500, demandLB:"عالٍ", demandGulf:"عالٍ جداً", difficulty:3, careers:["محاسب قانوني CPA","محلل مالي","CFO","مراجع Big 4"], desc:"كل شركة تحتاج محاسباً — استقرار وظيفي عالٍ. Big 4 يوظفون كثيراً من خريجي لبنان.", riasec:"CE", universities:["AUB","LAU","LIU","BAU"], roadmap:["رياضيات قوية","4 سنوات Accounting","CPA Exam","5 سنوات خبرة","ترقي لـCFO"], certifications:["CPA","CMA","CFA","ACCA"], skills:["Excel/Power BI","QuickBooks","IFRS","Financial Modeling","Audit"], aiImpact:"shifts", future:"الأتمتة تبتلع المحاسبة الروتينيّة؛ التحليل الماليّ والتدقيق والاستشارة تبقى عالية القيمة." },
  { id:12, slug:"digital-marketing", nameEn:"Digital Marketing", name:"تسويق رقمي", category:"الأعمال والإدارة", emoji:"📱", years:4, lang:"إنجليزي", salaryMin:900, salaryMax:1800, salaryGulfMin:2500, salaryGulfMax:4000, demandLB:"عالٍ جداً", demandGulf:"عالٍ جداً", difficulty:2, careers:["مدير تسويق","خبير SEO/SEM","Growth Hacker","Brand Manager"], desc:"أسرع التخصصات نمواً في العصر الرقمي. كل شركة تحتاج Digital Marketer.", riasec:"EA", universities:["LAU","AUB","LIU","NDU"], roadmap:["BAC أي فرع","4 سنوات Marketing","Google/Meta Certs","Portfolio مشاريع","Agency أو Brand"], certifications:["Google Ads","Meta Blueprint","HubSpot Marketing","SEMrush"], skills:["Google Analytics","Social Media","Content Strategy","SEO/SEM","Canva/Adobe"], aiImpact:"grows", future:"الذكاء الاصطناعي يضخّم المسوّق الماهر (محتوى/إعلانات/تحليل) ويجعله أسرع وأقوى." },
  { id:13, slug:"law", nameEn:"Law", name:"حقوق", category:"الحقوق والعلوم السياسية", emoji:"⚖️", years:4, lang:"فرنسي/عربي", salaryMin:1000, salaryMax:2200, salaryGulfMin:2800, salaryGulfMax:4500, demandLB:"متوسط", demandGulf:"متوسط", difficulty:3, careers:["محامٍ","قاضٍ","مستشار قانوني","Corporate Lawyer"], desc:"مهنة مرموقة تتطلب حدة التفكير. إمكانية الوصول لمراكز قيادية في الشركات والدولة.", riasec:"ES", universities:["USJ","LAU","AUB","UL"], roadmap:["BAC","Entrance Exam","4 سنوات حقوق","امتحان نقابة المحامين","محاماة/قضاء"], certifications:["نقابة المحامين","LLM للتخصص"], skills:["كتابة قانونية","بحث قانوني","تفاوض","إقناع","تحليل نصوص"], aiImpact:"shifts", future:"الذكاء الاصطناعي يتولّى البحث القانوني والعقود الروتينيّة؛ الترافع والتفاوض يبقيان بشريّين." },
  { id:14, slug:"political-science", nameEn:"Political Science", name:"علوم سياسية", category:"الحقوق والعلوم السياسية", emoji:"🌍", years:4, lang:"إنجليزي/فرنسي", salaryMin:900, salaryMax:1800, salaryGulfMin:2500, salaryGulfMax:4000, demandLB:"متوسط", demandGulf:"متوسط", difficulty:2, careers:["دبلوماسي","محلل سياسي","UN Officer","صحفي دولي"], desc:"فهم العالم وديناميكياته. ممتاز للعمل في المنظمات الدولية والسفارات.", riasec:"IS", universities:["AUB","LAU","USJ","NDU"], roadmap:["BAC","4 سنوات Pol Science","Master in IR أو Diplomacy","Internship أممي","مسار دبلوماسي"], certifications:["UN Courses","IELTS/TOEFL"], skills:["تحليل سياسي","كتابة تقارير","دبلوماسية","لغات أجنبية","بحث"], aiImpact:"shifts", future:"يتّجه نحو التحليل المعتمد على البيانات؛ القيمة في الفهم العميق واللغات والشبكات." },
  { id:15, slug:"media-journalism", nameEn:"Media & Journalism", name:"إعلام وصحافة", category:"الإعلام والفنون", emoji:"📰", years:4, lang:"عربي/إنجليزي", salaryMin:700, salaryMax:1500, salaryGulfMin:2000, salaryGulfMax:3500, demandLB:"متوسط", demandGulf:"متوسط", difficulty:2, careers:["صحفي","مذيع","مدير تحرير","Social Media Manager"], desc:"لبنان مركز إعلامي عربي رائد. الإعلام الرقمي والبودكاست فتحا فرصاً لا تعد.", riasec:"AE", universities:["LAU","AUB","USJ","NDU"], roadmap:["BAC","4 سنوات صحافة","تدريب محطة/صحيفة","بناء Portfolio","Digital Media"], certifications:["Google Journalism","Reuters Journalism"], skills:["كتابة صحفية","تصوير","مونتاج","Adobe Premiere","SEO للمحتوى"], aiImpact:"shifts", future:"الإعلام التقليدي يتقلّص بينما المحتوى الرقمي والبودكاست يفتحان أبواباً جديدة للمبدعين." },
  { id:16, slug:"graphic-design", nameEn:"Graphic Design", name:"تصميم غرافيكي", category:"الإعلام والفنون", emoji:"🎨", years:4, lang:"إنجليزي", salaryMin:800, salaryMax:1600, salaryGulfMin:2200, salaryGulfMax:3800, demandLB:"عالٍ", demandGulf:"عالٍ", difficulty:3, careers:["مصمم جرافيك","مصمم UX/UI","Motion Designer","Brand Identity"], desc:"إبداع بصري لا حدود له. الطلب متصاعد مع نمو الشركات الرقمية.", riasec:"AR", universities:["ALBA","LAU","NDU","USEK"], roadmap:["Portfolio إبداعي","4 سنوات تصميم","Adobe CC احترافي","مشاريع حقيقية","Studio/Freelance"], certifications:["Adobe Certified","Google UX Design","Figma Professional"], skills:["Adobe Photoshop","Illustrator","Figma","Motion Graphics","Typography"], aiImpact:"shifts", future:"أدوات AI صارت تنتج الصور؛ القيمة تنتقل إلى UX وهويّة العلامة والتفكير الإبداعي الاستراتيجي." },
  { id:17, slug:"education", nameEn:"Education", name:"تربية وتعليم", category:"التربية", emoji:"📚", years:4, lang:"عربي/فرنسي", salaryMin:700, salaryMax:1400, salaryGulfMin:2000, salaryGulfMax:3200, demandLB:"متوسط", demandGulf:"عالٍ", difficulty:2, careers:["معلم","مرشد تربوي","مدير مدرسة","Curriculum Developer"], desc:"من أنبل المهن. المدارس الدولية في الخليج تدفع رواتب مرتفعة للمعلمين المؤهلين.", riasec:"SA", universities:["LAU","LIU","NDU","UL"], roadmap:["BAC","4 سنوات تربية","تدريب ميداني","شهادة تعليم دولية","IB/Cambridge"], certifications:["CELTA","IB Certificate","Cambridge CELTA"], skills:["إدارة صف","تخطيط دروس","تواصل","تكنولوجيا تعليمية","لغات"], aiImpact:"grows", future:"المدارس الدوليّة في الخليج تطلب المعلّمين المؤهّلين بقوّة؛ مهنة آمنة من الأتمتة." },
  { id:18, slug:"psychology", nameEn:"Psychology", name:"علم نفس", category:"التربية", emoji:"🧠", years:4, lang:"إنجليزي/فرنسي", salaryMin:800, salaryMax:1600, salaryGulfMin:2200, salaryGulfMax:3500, demandLB:"عالٍ", demandGulf:"عالٍ", difficulty:3, careers:["معالج نفسي","مستشار HR","خبير تطوير","Psychologist"], desc:"الطلب يتزايد بشكل حاد. الاهتمام بالصحة النفسية ارتفع كثيراً.", riasec:"SI", universities:["USJ","LAU","AUB","NDU"], roadmap:["BAC","4 سنوات علم نفس","Master إكلينيكي","تدريب سريري","ترخيص مزاولة"], certifications:["Board Certified Psychologist","CBT Certificate"], skills:["تقييم نفسي","علاج معرفي سلوكي","إحصاء","تواصل","بحث"], aiImpact:"grows", future:"ارتفاع الوعي بالصحّة النفسيّة يرفع الطلب بحدّة؛ العلاج البشري لا يُستبدل." },
  { id:19, slug:"environmental-science", nameEn:"Environmental Science", name:"علوم بيئية", category:"العلوم", emoji:"🌿", years:4, lang:"إنجليزي", salaryMin:900, salaryMax:1800, salaryGulfMin:2200, salaryGulfMax:3800, demandLB:"متوسط", demandGulf:"عالٍ", difficulty:3, careers:["خبير بيئي","مستشار طاقة متجددة","ESG Analyst","UN Expert"], desc:"مستقبل الكوكب. الإمارات والسعودية تضخ مليارات في الاستدامة والطاقة الخضراء.", riasec:"IR", universities:["AUB","LAU","UOB","NDU"], roadmap:["علوم ورياضيات","4 سنوات بيئية","Master في Sustainability","شهادات بيئية","UN/NGO/Private Sector"], certifications:["LEED Green Associate","ISO 14001","ESG Analyst"], skills:["GIS/Remote Sensing","تقييم أثر بيئي","تحليل بيانات","Carbon Accounting"], aiImpact:"grows", future:"الاستدامة وESG يموّلهما مليارات الخليج؛ تخصّص صاعد بقوّة لعقود." },
  { id:20, slug:"mathematics-statistics", nameEn:"Mathematics & Statistics", name:"رياضيات وإحصاء", category:"العلوم", emoji:"📐", years:4, lang:"إنجليزي", salaryMin:1200, salaryMax:2400, salaryGulfMin:3000, salaryGulfMax:5000, demandLB:"متوسط", demandGulf:"عالٍ جداً", difficulty:5, careers:["Data Scientist","Actuary","Quant Analyst","AI Researcher"], desc:"أساس الذكاء الاصطناعي وعلم البيانات. الشركات التقنية تدفع أعلى الرواتب لعلماء البيانات.", riasec:"IC", universities:["AUB","LAU","LIU","UL"], roadmap:["رياضيات استثنائية","4 سنوات رياضيات","Master in Data Science/Stats","تدريب تقني","وظيفة FAANG"], certifications:["Google Data Analytics","Tableau Certified","Azure Data Scientist"], skills:["Python/R","Machine Learning","Statistics","Linear Algebra","Data Visualization"], aiImpact:"grows", future:"أساس الذكاء الاصطناعي وعلم البيانات؛ من أعلى التخصّصات أجراً وطلباً عالميّاً." },
  { id:21, slug:"artificial-intelligence", nameEn:"Artificial Intelligence", name:"ذكاء اصطناعي وتعلم الآلة", category:"الهندسة والتكنولوجيا", emoji:"🤖", years:4, lang:"إنجليزي", salaryMin:1800, salaryMax:3500, salaryGulfMin:4500, salaryGulfMax:7500, demandLB:"عالٍ جداً", demandGulf:"عالٍ جداً", difficulty:5, careers:["AI Engineer","ML Engineer","Research Scientist","NLP Engineer"], desc:"أسرع تخصص نمواً في العالم. الشركات الكبرى كـ Google وMeta وMicrosoft تتنافس على خريجي الذكاء الاصطناعي.", riasec:"IR", universities:["AUB","LAU","AUT","LIU"], roadmap:["رياضيات + برمجة قوية","4 سنوات CS/AI","Master in ML","مشاريع Kaggle/GitHub","وظيفة Big Tech"], certifications:["TensorFlow Developer","AWS ML Specialty","Deep Learning Specialization","PyTorch Certified"], skills:["Python","TensorFlow/PyTorch","Deep Learning","NLP","Computer Vision","Statistics"], aiImpact:"grows", future:"أسرع تخصّص نموّاً عالميّاً؛ هو نفسه محرّك ثورة الذكاء الاصطناعي." },
  { id:22, slug:"data-science", nameEn:"Data Science", name:"علم البيانات", category:"الهندسة والتكنولوجيا", emoji:"📊", years:4, lang:"إنجليزي", salaryMin:1600, salaryMax:3000, salaryGulfMin:4000, salaryGulfMax:6500, demandLB:"عالٍ جداً", demandGulf:"عالٍ جداً", difficulty:4, careers:["Data Scientist","Data Analyst","BI Developer","Product Analyst"], desc:"كل شركة تحتاج Data Scientist. لبنان يصدّر مواهب تقنية للعالم — الطلب يتضاعف سنوياً.", riasec:"IC", universities:["AUB","LAU","AUT","LIU"], roadmap:["رياضيات + Python","4 سنوات CS أو Data Science","Bootcamp أو مشاريع","Portfolio قوي","وظيفة"], certifications:["Google Data Analytics","IBM Data Science","Power BI Certified","Tableau"], skills:["Python","SQL","Power BI/Tableau","Pandas","Machine Learning","Statistics"], aiImpact:"grows", future:"كل شركة تحتاج علم البيانات؛ الطلب يتضاعف سنويّاً والقيمة في فهم الأعمال + النمذجة." },
  { id:23, slug:"cybersecurity", nameEn:"Cybersecurity", name:"أمن المعلومات والشبكات", category:"الهندسة والتكنولوجيا", emoji:"🔐", years:4, lang:"إنجليزي", salaryMin:1600, salaryMax:3000, salaryGulfMin:4000, salaryGulfMax:6500, demandLB:"عالٍ جداً", demandGulf:"عالٍ جداً", difficulty:4, careers:["Cybersecurity Analyst","Penetration Tester","Security Architect","CISO"], desc:"ثغرات أمنية تكلف مليارات. الشركات تدفع رواتب خيالية لحماية بياناتها — نقص حاد في الكوادر.", riasec:"IR", universities:["AUB","LAU","AUT","LIU"], roadmap:["شبكات + برمجة","4 سنوات Cybersecurity أو CS","OSCP أو CEH","Bug Bounty Hunting","وظيفة"], certifications:["OSCP","CEH","CompTIA Security+","CISSP","Cisco CyberOps"], skills:["Networking","Linux","Python","Penetration Testing","Forensics","SIEM"], aiImpact:"grows", future:"نقص حادّ عالمي في الكوادر ورواتب مرتفعة؛ الطلب يتصاعد مع تزايد الهجمات." },
  { id:24, slug:"biomedical-engineering", nameEn:"Biomedical Engineering", name:"هندسة طبية حيوية", category:"الطب والصحة", emoji:"🔬", years:5, lang:"إنجليزي", salaryMin:1500, salaryMax:2800, salaryGulfMin:3800, salaryGulfMax:6000, demandLB:"عالٍ", demandGulf:"عالٍ جداً", difficulty:5, careers:["Biomedical Engineer","Medical Device Designer","Clinical Engineer","R&D Specialist"], desc:"الجسر بين الطب والهندسة. تصميم الأجهزة الطبية والروبوتات الجراحية — مستقبل الرعاية الصحية.", riasec:"IR", universities:["AUB","LAU","AUT","BAU"], roadmap:["رياضيات وعلوم قوية","5 سنوات هندسة طبية","تدريب مستشفى/شركة","شهادات متخصصة","وظيفة"], certifications:["Certified Biomedical Engineer","PMP","FDA Regulatory"], skills:["MATLAB","SolidWorks","Electronics","Programming","Medical Imaging","Regulatory Affairs"], aiImpact:"grows", future:"الأجهزة الطبيّة والروبوتات الجراحيّة مستقبل الرعاية الصحيّة؛ تخصّص صاعد عالي القيمة." },
  { id:25, slug:"physical-therapy", nameEn:"Physical Therapy", name:"علاج فيزيائي", category:"الطب والصحة", emoji:"🦴", years:4, lang:"إنجليزي/فرنسي", salaryMin:1000, salaryMax:2000, salaryGulfMin:2500, salaryGulfMax:4000, demandLB:"عالٍ", demandGulf:"عالٍ جداً", difficulty:3, careers:["معالج فيزيائي","أخصائي إعادة تأهيل","مدير وحدة PT","مدرب رياضي"], desc:"طلب متصاعد مع تزايد الوعي بإعادة التأهيل. المستشفيات والأندية الرياضية والخليج يحتاجون متخصصين.", riasec:"SI", universities:["LAU","USJ","BAU","LIU"], roadmap:["BAC علوم","4 سنوات علاج فيزيائي","تدريب سريري","ترخيص وزارة الصحة","تخصص رياضي اختياري"], certifications:["NPTAE","PTA Board","IASTM Certified"], skills:["تقييم حركي","تمارين علاجية","Ultrasound/TENS","تشريح","توثيق سريري"], aiImpact:"grows", future:"مهنة آمنة من الأتمتة (لمس وعلاج بشري)؛ طلب متصاعد مع الوعي بإعادة التأهيل." },
  { id:26, slug:"nutrition", nameEn:"Nutrition & Food Science", name:"تغذية وعلوم غذائية", category:"الطب والصحة", emoji:"🥗", years:4, lang:"إنجليزي/فرنسي", salaryMin:800, salaryMax:1600, salaryGulfMin:2000, salaryGulfMax:3500, demandLB:"عالٍ", demandGulf:"عالٍ", difficulty:3, careers:["أخصائي تغذية","مستشار صحة","Food Technologist","صحفي تغذية"], desc:"الوعي الصحي يرفع الطلب سنوياً. المستشفيات والنوادي والمؤسسات الغذائية كلها تحتاج أخصائيين.", riasec:"SI", universities:["AUB","LAU","USJ","LIU"], roadmap:["BAC علوم","4 سنوات تغذية","تدريب سريري 6 أشهر","ترخيص نقابة التغذية","عيادة أو مستشفى"], certifications:["RDN (Registered Dietitian)","CSSD للتغذية الرياضية"], skills:["تحليل غذائي","تخطيط وجبات","كيمياء غذاء","HACCP","تواصل مع مرضى"], aiImpact:"grows", future:"الوعي الصحّي والوقاية يرفعان الطلب؛ مجال ينمو في المستشفيات والرياضة والصناعة الغذائيّة." },
  { id:27, slug:"hospitality-tourism", nameEn:"Hospitality & Tourism", name:"فندقة وإدارة سياحة", category:"الأعمال والإدارة", emoji:"🏨", years:4, lang:"إنجليزي/فرنسي", salaryMin:800, salaryMax:1700, salaryGulfMin:2500, salaryGulfMax:4200, demandLB:"متوسط", demandGulf:"عالٍ جداً", difficulty:2, careers:["مدير فندق","Event Planner","Travel Manager","F&B Director"], desc:"قطاع ضخم في الخليج وأوروبا. الإمارات تحتاج آلاف الكوادر الفندقية المؤهلة سنوياً.", riasec:"ES", universities:["LAU","LIU","NDU","USEK"], roadmap:["BAC","4 سنوات فندقة","تدريب في فندق 5 نجوم","تخصص F&B أو Rooms","وظيفة فندق دولي"], certifications:["CPHQ","Certified Hotel Administrator","WSET Level 3"], skills:["Customer Service","Event Management","Revenue Management","اللغات","F&B Operations"], aiImpact:"grows", future:"سياحة الخليج (السعوديّة/الإمارات/قطر) توظّف آلافاً سنويّاً؛ قطاع يعتمد على اللمسة البشريّة." },
  { id:28, slug:"logistics-supply-chain", nameEn:"Logistics & Supply Chain", name:"لوجستيات وسلسلة التوريد", category:"الأعمال والإدارة", emoji:"🚢", years:4, lang:"إنجليزي", salaryMin:1000, salaryMax:2000, salaryGulfMin:3000, salaryGulfMax:4800, demandLB:"عالٍ", demandGulf:"عالٍ جداً", difficulty:3, careers:["Supply Chain Manager","Logistics Analyst","Procurement Officer","Operations Manager"], desc:"التجارة العالمية تتوقف على اللوجستيات. دبي وقناة السويس وميناء بيروت محطات حيوية تحتاج كوادر.", riasec:"CE", universities:["AUB","LAU","LIU","AUT"], roadmap:["BAC","4 سنوات لوجستيات أو أعمال","تدريب في شركة شحن","CSCMP أو APICS","وظيفة"], certifications:["CSCP (APICS)","CLTD","Six Sigma Green Belt","PMP"], skills:["SAP/Oracle","Warehouse Management","ERP Systems","Negotiation","Data Analysis"], aiImpact:"shifts", future:"أتمتة المستودعات تتزايد؛ القيمة في التخطيط الاستراتيجي وإدارة المخاطر والبيانات." },
  { id:29, slug:"mechanical-engineering", nameEn:"Mechanical Engineering", name:"هندسة ميكانيكية", category:"الهندسة والتكنولوجيا", emoji:"⚙️", years:5, lang:"إنجليزي", salaryMin:1200, salaryMax:2300, salaryGulfMin:3200, salaryGulfMax:5200, demandLB:"متوسط", demandGulf:"عالٍ جداً", difficulty:4, careers:["مهندس ميكانيكي","مهندس طاقة","مهندس إنتاج","مهندس HVAC"], desc:"أساس كل صناعة — من السيارات للطائرات. الخليج تصنيع ومصافٍ ومشاريع ضخمة لا تتوقف.", riasec:"RI", universities:["AUB","LAU","AUT","BAU"], roadmap:["رياضيات وفيزياء","5 سنوات هندسة ميكانيكية","تدريب صناعي","AutoCAD/SolidWorks","وظيفة"], certifications:["PE License","SolidWorks Certified","PMP","Six Sigma"], skills:["SolidWorks/AutoCAD","Thermodynamics","HVAC","Fluid Mechanics","FEA/FEM"], aiImpact:"shifts", future:"تصنيع الخليج ومشاريعه الضخمة تدفع الطلب؛ الذكاء الاصطناعي أداة محاكاة وتصميم." },
  { id:30, slug:"telecom-engineering", nameEn:"Telecommunications Engineering", name:"هندسة اتصالات وشبكات", category:"الهندسة والتكنولوجيا", emoji:"📡", years:5, lang:"إنجليزي", salaryMin:1500, salaryMax:2800, salaryGulfMin:3800, salaryGulfMax:6000, demandLB:"عالٍ", demandGulf:"عالٍ جداً", difficulty:4, careers:["Network Engineer","Telecom Specialist","5G Engineer","IoT Developer"], desc:"5G والإنترنت من الأشياء يفجران الطلب. شركات الاتصالات الكبرى تتسابق على المهندسين المؤهلين.", riasec:"IR", universities:["AUB","LAU","AUT","LIU"], roadmap:["فيزياء ورياضيات قوية","5 سنوات اتصالات","Cisco/Huawei Certs","5G Specialization","وظيفة دولية"], certifications:["CCNP","CCIE","Ericsson 5G","Huawei Certified"], skills:["MATLAB","RF Engineering","Network Protocols","Fiber Optics","5G/LTE","Python"], aiImpact:"grows", future:"5G وإنترنت الأشياء يفجّران الطلب؛ بنية تحتيّة رقميّة تتوسّع لعقود." },
  { id:31, slug:"film-production", nameEn:"Film & Visual Production", name:"سينما وإنتاج مرئي", category:"الإعلام والفنون", emoji:"🎬", years:4, lang:"إنجليزي/عربي", salaryMin:700, salaryMax:1600, salaryGulfMin:2200, salaryGulfMax:4000, demandLB:"متوسط", demandGulf:"عالٍ", difficulty:3, careers:["مخرج","محرر فيديو","منتج محتوى","Content Creator","VFX Artist"], desc:"ثورة المحتوى الرقمي وYouTube وNetflix فتحت أبواباً لا تُعد. الإنتاج البصري طلبه يتضاعف.", riasec:"AR", universities:["ALBA","LAU","NDU","AUST"], roadmap:["Portfolio إبداعي","4 سنوات سينما أو إعلام","تدريب في شركة إنتاج","Adobe Premiere احترافي","مشاريع مستقلة"], certifications:["Adobe Certified Expert","DaVinci Resolve Certified"], skills:["Adobe Premiere","After Effects","DaVinci Resolve","Cinematography","Storytelling"], aiImpact:"shifts", future:"ثورة المحتوى الرقمي تفتح أبواباً؛ أدوات AI تسرّع الإنتاج والقيمة في السرد والرؤية." },
  { id:32, slug:"social-work", nameEn:"Social Work & Development", name:"خدمة اجتماعية وتنمية", category:"التربية", emoji:"🤝", years:4, lang:"عربي/إنجليزي", salaryMin:700, salaryMax:1500, salaryGulfMin:2000, salaryGulfMax:3200, demandLB:"عالٍ", demandGulf:"متوسط", difficulty:2, careers:["أخصائي اجتماعي","مدير NGO","مستشار تنمية","موظف أممي"], desc:"لبنان مركز للمنظمات الدولية والإنسانية. UNHCR وUNICEF وعشرات المنظمات تحتاج متخصصين.", riasec:"SA", universities:["LAU","AUB","USJ","LIU"], roadmap:["BAC","4 سنوات خدمة اجتماعية","تدريب NGO","ماستر تنمية مستدامة","UN/INGO"], certifications:["CSW Certificate","Project Cycle Management","MEAL Training"], skills:["إدارة مشاريع","تقرير وتوثيق","قيادة مجتمعية","بحث اجتماعي","لغات أجنبية"], aiImpact:"grows", future:"المنظّمات الدوليّة والإنسانيّة تطلب بقوّة؛ مهنة إنسانيّة آمنة من الأتمتة." },
];

export const MAJORS_BY_SLUG: Record<string, Major> = Object.fromEntries(MAJORS.map((m) => [m.slug, m]));

// id → slug, so the list page (which keeps its own copy of the data for the
// interactive UI) can link each card to its SEO detail page /majors/[slug].
export const SLUG_BY_ID: Record<number, string> = Object.fromEntries(MAJORS.map((m) => [m.id, m.slug]));

export const MAJOR_CATEGORIES = ["الكل", ...Array.from(new Set(MAJORS.map((m) => m.category)))];

export const AI_IMPACT_LABEL: Record<AiImpact, { label: string; emoji: string; tone: string }> = {
  grows:   { label: "في نموّ", emoji: "🟢", tone: "bg-emerald-100 text-emerald-700 border-emerald-300" },
  shifts:  { label: "يتحوّل", emoji: "🟡", tone: "bg-amber-100 text-amber-700 border-amber-300" },
  at_risk: { label: "مهدّد", emoji: "🔴", tone: "bg-rose-100 text-rose-700 border-rose-300" },
};
