-- ============================================================================
-- SOCIAL SYSTEM · PHASE 1 — Academic Profile (public discovery)
-- ----------------------------------------------------------------------------
-- Activates the public-profile scaffolding that already exists on
-- student_profiles (is_public, public_slug) but was never wired up.
--
-- Design notes:
--  * We DO NOT open student_profiles to public SELECT — it holds PII
--    (email, phone, date_of_birth, gpa, bac_grade). Public reads go through a
--    SECURITY DEFINER RPC that returns ONLY a curated, safe projection.
--  * public_slug is auto-generated by a trigger the first time a profile is
--    made public, so the client never has to manage slug uniqueness.
--  * Additive only — nothing here changes existing rows' data or breaks the
--    /student/[masarakId] ID-card feature (that uses a different RPC).
-- ============================================================================

-- 1) Unique, case-insensitive-safe slug index (partial: only non-null slugs) ---
CREATE UNIQUE INDEX IF NOT EXISTS student_profiles_public_slug_key
  ON public.student_profiles (public_slug)
  WHERE public_slug IS NOT NULL;

-- 2) Slug generator — readable base from the name + a stable suffix from the
--    user_id, with a collision guard. Keeps latin + Arabic letters + digits.
CREATE OR REPLACE FUNCTION public.gen_profile_slug(p_name text, p_user_id uuid)
RETURNS text
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public', 'pg_catalog'
AS $$
DECLARE
  base      text;
  suffix    text;
  candidate text;
  n         int := 6;
BEGIN
  base := lower(regexp_replace(coalesce(nullif(btrim(p_name), ''), 'student'),
                               '[^a-z0-9؀-ۿ]+', '-', 'gi'));
  base := btrim(base, '-');
  IF base IS NULL OR base = '' THEN base := 'student'; END IF;
  base := left(base, 40);

  LOOP
    suffix    := left(replace(p_user_id::text, '-', ''), n);
    candidate := base || '-' || suffix;
    EXIT WHEN NOT EXISTS (
      SELECT 1 FROM public.student_profiles
      WHERE public_slug = candidate AND user_id <> p_user_id
    );
    n := n + 2;
    EXIT WHEN n > 32;   -- practically unreachable; guards against infinite loop
  END LOOP;

  RETURN candidate;
END;
$$;

-- 3) Trigger — assign a slug the first time the profile becomes public --------
CREATE OR REPLACE FUNCTION public.tg_student_profiles_slug()
RETURNS trigger
LANGUAGE plpgsql
SET search_path TO 'public', 'pg_catalog'
AS $$
BEGIN
  IF NEW.is_public IS TRUE AND (NEW.public_slug IS NULL OR NEW.public_slug = '') THEN
    NEW.public_slug := public.gen_profile_slug(NEW.full_name, NEW.user_id);
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS student_profiles_slug ON public.student_profiles;
CREATE TRIGGER student_profiles_slug
  BEFORE INSERT OR UPDATE OF is_public, full_name
  ON public.student_profiles
  FOR EACH ROW
  EXECUTE FUNCTION public.tg_student_profiles_slug();

-- 4) Backfill slugs for anyone already public --------------------------------
UPDATE public.student_profiles
SET public_slug = public.gen_profile_slug(full_name, user_id)
WHERE is_public = true AND (public_slug IS NULL OR public_slug = '');

-- 5) Public read RPC — curated SAFE projection (no PII) -----------------------
CREATE OR REPLACE FUNCTION public.get_public_academic_profile(p_slug text)
RETURNS json
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path TO 'public', 'pg_catalog'
AS $$
DECLARE
  v_prof   public.student_profiles%ROWTYPE;
  v_up     public.user_profiles%ROWTYPE;
  v_badges json;
BEGIN
  SELECT * INTO v_prof
  FROM public.student_profiles
  WHERE public_slug = p_slug AND is_public = true
  LIMIT 1;

  IF NOT FOUND THEN
    RETURN NULL;
  END IF;

  SELECT * INTO v_up FROM public.user_profiles WHERE id = v_prof.user_id LIMIT 1;

  SELECT json_agg(ua.badge_code) INTO v_badges
  FROM public.user_achievements ua
  WHERE ua.user_id = v_prof.user_id;

  RETURN json_build_object(
    'slug',                   v_prof.public_slug,
    'user_id',                v_prof.user_id,
    'full_name',              v_prof.full_name,
    'avatar_url',             v_prof.avatar_url,
    'bio',                    v_prof.bio,
    'city',                   v_prof.city,
    'country_code',           v_up.country_code,
    'grade_level',            v_prof.grade_level,
    'school_name',            v_prof.school_name,
    'university_name',        v_prof.university_name,
    'major',                  v_prof.major,
    'interests',              v_prof.interests,
    'skills',                 v_prof.skills,
    'languages',              v_prof.languages,
    'personality_type',       v_prof.personality_type,
    'career_dna_completed',   v_prof.career_dna_completed,
    'preferred_majors',       v_prof.preferred_majors,
    'preferred_universities', v_prof.preferred_universities,
    'graduation_year',        v_prof.graduation_year,
    'social_links',           v_prof.social_links,
    'xp',                     coalesce(v_prof.xp, v_prof.xp_points, 0),
    'level',                  coalesce(v_prof.level, 1),
    'streak_days',            coalesce(v_prof.streak_days, 0),
    'badges',                 coalesce(v_badges, '[]'::json),
    'created_at',             v_prof.created_at
  );
END;
$$;

GRANT EXECUTE ON FUNCTION public.get_public_academic_profile(text) TO anon, authenticated;
