-- ============================================================================
-- Web Push subscriptions (growth strategy M1 — recall channel).
-- ----------------------------------------------------------------------------
-- Stores each browser's push subscription (endpoint + keys) per user. Rows are
-- written by the client after the user grants notification permission, and read
-- by the daily-reminder cron (service role) to send pushes. RLS: own rows only.
-- NOT auto-applied — run in the SQL editor after review.
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.web_push_subscriptions (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  endpoint   text NOT NULL UNIQUE,
  p256dh     text NOT NULL,
  auth       text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_web_push_subs_user ON public.web_push_subscriptions(user_id);

ALTER TABLE public.web_push_subscriptions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS wps_own_select ON public.web_push_subscriptions;
CREATE POLICY wps_own_select ON public.web_push_subscriptions
  FOR SELECT USING (user_id = (SELECT auth.uid()));

DROP POLICY IF EXISTS wps_own_insert ON public.web_push_subscriptions;
CREATE POLICY wps_own_insert ON public.web_push_subscriptions
  FOR INSERT WITH CHECK (user_id = (SELECT auth.uid()));

DROP POLICY IF EXISTS wps_own_update ON public.web_push_subscriptions;
CREATE POLICY wps_own_update ON public.web_push_subscriptions
  FOR UPDATE USING (user_id = (SELECT auth.uid())) WITH CHECK (user_id = (SELECT auth.uid()));

DROP POLICY IF EXISTS wps_own_delete ON public.web_push_subscriptions;
CREATE POLICY wps_own_delete ON public.web_push_subscriptions
  FOR DELETE USING (user_id = (SELECT auth.uid()));
